# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote.proto

require 'google/protobuf'
require_relative 'types_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("remote.proto", :syntax => :proto3) do
    add_message "prometheus.WriteRequest" do
      repeated :timeseries, :message, 1, "prometheus.TimeSeries"
    end
    add_message "prometheus.ReadRequest" do
      repeated :queries, :message, 1, "prometheus.Query"
      repeated :accepted_response_types, :enum, 2, "prometheus.ReadRequest.ResponseType"
    end
    add_enum "prometheus.ReadRequest.ResponseType" do
      value :SAMPLES, 0
      value :STREAMED_XOR_CHUNKS, 1
    end
    add_message "prometheus.ReadResponse" do
      repeated :results, :message, 1, "prometheus.QueryResult"
    end
    add_message "prometheus.Query" do
      optional :start_timestamp_ms, :int64, 1
      optional :end_timestamp_ms, :int64, 2
      repeated :matchers, :message, 3, "prometheus.LabelMatcher"
      optional :hints, :message, 4, "prometheus.ReadHints"
    end
    add_message "prometheus.QueryResult" do
      repeated :timeseries, :message, 1, "prometheus.TimeSeries"
    end
    add_message "prometheus.ChunkedReadResponse" do
      repeated :chunked_series, :message, 1, "prometheus.ChunkedSeries"
      optional :query_index, :int64, 2
    end
  end
end

module Prometheus
  WriteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.WriteRequest").msgclass
  ReadRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.ReadRequest").msgclass
  ReadRequest::ResponseType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.ReadRequest.ResponseType").enummodule
  ReadResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.ReadResponse").msgclass
  Query = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.Query").msgclass
  QueryResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.QueryResult").msgclass
  ChunkedReadResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.ChunkedReadResponse").msgclass
end
