
name: Push Cortex Client
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.64.1
        with:
          ruby-version: 2.5.0

      - name: Install Dependencies
        run: gem install bundler -v 2.0.2

      - name: Install Gems
        run: bundle install

      - name: Run Tests
        run: rspec

      - name: Lint check
        run: rubocop

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: sh push-gem.sh